name: legendary_marvel_db
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.1.0
  intl: ^0.17.0
  provider: ^6.0.1
  flutter_svg: ^0.23.0+1
  flutter_icons: ^1.1.0
  badges: ^2.0.2
  json_annotation: ^4.4.0
  built_collection: ^5.1.1
  built_value: ^8.1.3
  carousel_slider: ^4.0.0
  cached_network_image: ^3.2.0
  data_table_2: ^2.2.0
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  built_value_generator: ^8.1.3
  json_serializable: ^6.1.0
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/teams/
    - assets/images/attributes/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic
          weight: 400

flutter_icons:
  ios: true
  image_path: "assets/icon/launcher_icon.png"
